// <auto-generated />
using System;
using Leasing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Leasing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LeasingDbContext))]
    [Migration("20250903061123_RemoveSuccesorId")]
    partial class RemoveSuccesorId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("leasing")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Leasing.Domain.Entities.Lease", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Credit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DepositHeld")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DepositRequired")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("MonthlyRent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("NextDueDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("PreviousLeaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PreviousLeaseId")
                        .IsUnique()
                        .HasFilter("[PreviousLeaseId] IS NOT NULL");

                    b.HasIndex("ApartmentId", "IsActive");

                    b.HasIndex("TenantId", "ApartmentId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("TenantId", "IsActive");

                    b.ToTable("Leases", "leasing", t =>
                        {
                            t.HasCheckConstraint("CK_Leases_Dates_Order", "[EndDate] IS NULL OR [EndDate] >= [StartDate]");

                            t.HasCheckConstraint("CK_Leases_Deposits_NonNegative", "[DepositRequired] >= 0 AND [DepositHeld] >= 0");
                        });
                });

            modelBuilder.Entity("Leasing.Domain.Entities.Lease", b =>
                {
                    b.HasOne("Leasing.Domain.Entities.Lease", null)
                        .WithMany()
                        .HasForeignKey("PreviousLeaseId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
